### ISSUE TITLE
Toga widgets misaligned under Gtk when using themes

### ISSUE THREAD

**Issue by ArchKudo** [pybee/toga#384] opened 2018-03-02 04:21 UTC
I tried running some of the tutorials in the `examples/` directory , But some widgets appear to be shifted up, or getting out of the main window.

## Steps to reproduce
```bash
$ python -m tutorial0
```
## Expected Behavior
Something resembling this:
![From toga.readthedocs.io](https://toga.readthedocs.io/en/latest/_images/tutorial-0.png)

## Current Behavior
![Imgur](https://i.imgur.com/lPmH65j.png?1)

More examples: [Imgur Album](https://imgur.com/a/xVsKi)

## Your Environment

* Python Version (list the specific version number):
 Python 3.6.4 (default, Feb 24 2018, 17:38:07) 
[GCC 7.3.0] on linux

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [x] Linux - ArchLinux(4.15.4-1, x86_64): Gnome version: GNOME Shell 3.26.2 Theme: [Materia](https://github.com/nana-4/materia-theme)
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [x] gtk (gtk3 3.22.28-1)
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment] 2018-03-02 04:52
Looks like a duplicate of #336. The underlying problem appears to be getting the geometry of the window itself when GTK has a menu bar *in* the window.

**Closed by freakboy3742** 2018-03-02 04:52 UTC
Labels: duplicate
