### ISSUE TITLE
Mac menubar/tray app?

### ISSUE THREAD

**Issue by rucuriousyet** [pybee/toga#183] opened 2017-06-17 21:29 UTC
Would it be possible at this point to create a MacOS menubar/tray app with Toga?

**Comment by Ocupe** [comment] 2017-06-17 21:44
Hey @rucuriousyet,
Toga is still in its early stages.
I hope somebody will correct me if I'm wrong, but at the moment there is no support for a menubar app. If you would like to add such a feature you are more than welcome.

**Comment by freakboy3742** [comment] 2017-06-18 01:52
@rucuriousyet Like @Ocupe said, it's not currently possible - but it's definitely on the list of things we want to support.

**Comment by freakboy3742** [comment] 2017-12-29 01:26
I'm going to close this as a duplicate of #97 - although the language there is Windows specific (Systray, rather than menubar/tray), the underlying idea is the same - and the Toga approach will be to build a cross-platform abstraction of the underlying idea.

**Closed by freakboy3742** 2017-12-29 01:26 UTC
