### ISSUE TITLE
GTK warning when running the toga-demo

### ISSUE THREAD

**Issue by yogin25** [pybee/toga#93] opened 2017-01-03 23:38 UTC
When lunching the toga demo on my arch box under virtualenv a warning was displayed by GTK in  the terminal

(toga-demo:4212): Gtk-WARNING **: Allocating size to GtkButton 0x21c5dc0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

As I said, i am running Archlinux with gtk3.22.5-1
Architecture: x86_64

**Comment by freakboy3742** [comment] 2017-01-09 01:09
Closing as a duplicate of #73 - I don't know enough about Arch to be able to debug this one, though.

**Closed by freakboy3742** 2017-01-09 01:09 UTC

**Comment by gCurse** [comment] 2017-02-19 13:45
This is not distribution related. The same happens on Lubuntu 16.10.
Definetly not a duplicate of #73.
As the warning says GTK wants you to call gtk_widget_get_preferred_width() and _height() before allocating size.
