### ISSUE TITLE
Unhandled Exception: Python.Runtime.PythonException: FileNotFoundException : Could not find file 

### ISSUE THREAD

**Issue by AdnanMuhib** [pybee/toga#571] opened 2018-07-28 19:40 UTC
## Expected Behavior
Simply Running hello World Example after fresh installation in fresh virtual environment. And Exception occurred. It should run the hello world without any error. As mentioned in the error Exception file not found so it was easier for me to figure out the possible solution. I opened the directory mentioned in the error, there was a png icon file, I converted that file to .ico file with name tiberius.ico and saved in the same directory (resources). Booom it fixed the issue.
I Should have create a PR instead but I don't know where to place the right code for package to copy the ico file along with installation package.

## Current Behavior
Unhandled Exception: Python.Runtime.PythonException: FileNotFoundException : Could not find file 'C:\Program Files\Anaconda2\envs\BeeWare\lib\site-packages\toga\resources\tiberius.ico'.
## Steps to reproduce

1. New Virtual Env

2. helloworld.py sample code from the docs.

3. ``python -m helloworld`` 

4. boom, Error Occured
![image](https://user-images.githubusercontent.com/18069154/43359992-0bd1f2fa-92c7-11e8-8e6d-25416dc20f46.png)

## Your Environment
* Python Version 3.6.4

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [x] Windows 10- version:1803 Build 17134.165
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms 
  - [x] win32
  - [ ] Other (please specify)

## Solution
place tiberius.ico file in the resources directory of installation package.

![image](https://user-images.githubusercontent.com/18069154/43360045-dbe4b0ea-92c7-11e8-95d4-0e5ba18558e9.png)

**Comment by freakboy3742** [comment] 2018-07-29 00:51
Thanks for the report - I'm fairly certain this is a duplicate of #567. This has been corrected in master, and the fix will be included in 0.3.0.dev10.

**Closed by freakboy3742** 2018-07-29 00:51 UTC

**Comment by radztech** [comment] 2018-09-22 07:27
the file was missing from my installation

**Comment by berkobob** [comment] 2018-10-01 14:30
Mine too
