### ISSUE TITLE
"No module named 'toga'" after installation

### ISSUE THREAD

**Issue by bityob** [pybee/toga#67] opened 2016-09-23 09:33 UTC
I installed toga (and verified it is truly updated):

```
C:\Users\myuser>pip install -U toga
Requirement already up-to-date: toga in d:\python35\lib\site-packages
Requirement already up-to-date: toga-win32; sys_platform == "win32" in d:\python35\lib\site-packages (from toga)
Requirement already up-to-date: toga-cassowary in d:\python35\lib\site-packages (from toga-win32; sys_platform == "win32"->toga)
Requirement already up-to-date: cassowary in d:\python35\lib\site-packages (from toga-cassowary->toga-win32; sys_platform == "win32"->toga)
```

but when I try to use it, I get "No module named 'toga'"

```
C:\Users\myuser>python
Python 3.5.2 |Anaconda 2.5.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import toga
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'toga'
```

This my watermark:

```
In [8]: %watermark
2016-09-23T12:23:27+03:00

CPython 3.5.2
IPython 4.1.1

compiler   : MSC v.1900 64 bit (AMD64)
system     : Windows
release    : 10
machine    : AMD64
processor  : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
CPU cores  : 8
interpreter: 64bit
```

**Comment by freakboy3742** [comment] 2016-09-27 05:16
Unfortunately, Windows support is lagging a bit behind other platforms; some recent changes haven't been reflected in the Windows port. 

Closing as an effective duplicate of pybee/toga-demo#4

**Closed by freakboy3742** 2016-09-27 05:16 UTC
