### ISSUE TITLE
##TypeError: 'ObjCInstance' object is not callable

### ISSUE THREAD

**Issue by 1rjun** [pybee/toga#389] opened 2018-03-04 18:56 UTC
## Expected Behavior

I have successfully installed the toga in my macOS but its showing error when I run
When I try to run the ```toga-demo``` in my terminal it shows me error

## Current Behavior

showing me error 
```
TypeError: 'ObjCInstance' object is not callable
```

## Your Environment

* Python Version (list the specific version number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] macOS - version: High Sierra
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

**Comment by freakboy3742** [comment] 2018-03-04 23:17
This is almost certainly a duplicate of #243.

**Closed by freakboy3742** 2018-03-04 23:17 UTC
