### ISSUE TITLE
App.exit() overwrite doesn't work on Windows / winforms

### ISSUE THREAD

**Issue by stantonxu** [pybee/toga#475] opened 2018-05-13 05:03 UTC
## Expected Behavior

Issue for App.exit(). I overwrite the exit() by adding some file processing actions in my own app, like class Notebook(toga.App), and then called super().exit(). This exit() seems got called on Mac when I closed the App, but it is not called on Windows.

App code here, https://github.com/stantonxu/Notebook/blob/CodeClean/notebook.py

## Current Behavior

The file processing actions were proceeded on Mac when the app is closed, but not proceeded on Windows.

## Steps to reproduce

1. Overwrite the App.exit() by adding some functions to call.

2. Close the App, the functions are not called on Windows.

## Your Environment

* Python Version (list the specific version number)
3.6.4

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [*] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [*] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by stantonxu** [comment] 2018-05-13 05:04
Please associate this issue with PR#474

**Comment by stantonxu** [comment] 2018-05-13 06:09
More testing...

This fix partially fix the problem. Now it works if I click the menu "File -> Exit", but it doesn't work if I click the "X" button of the window to close the app.

**Comment by stantonxu** [comment] 2018-05-13 06:09
On Mac, both the "X" button and the "Python -> Quit Notebook" menu work
On Windows, neither the "X" button nor the Exit menu work

**Comment by obulat** [comment] 2018-05-18 04:59
I've tried to debug this, but it seems to be a bigger issue than I though at first. And the reason, I suspect, is in the different ways that Windows and Mac handle window closing and sharing of responsibilities between App and Window. 

When you click on 'x' sign in the top right corner, you, in fact, call native `Form.Close()`. It closes the Window, and, if this window is the main window in the app, it also calls `App.Exit()` to exit from the app.
When you click Exit Application in the menu, you call native `App.Exit()` function, which, in turn, checks if any windows are open and closes them. When closing the main window, it, again, calls `Form.Close()`, which, in turn, calls `App.Exit()`. 

This is the reason why in my patch some of the exit functions are called twice or even more times. 

I'm not sure how it is done on Mac and other platforms, but I think we need to somehow synchronize the exiting. 
Also, we could have an `on_exit()` in the interface, which would be easier to handle in all backends instead of overriding `exit()` function. 

In my patch I tried to use the Winforms native Application.Exit event handler, but at that moment all the widgets are disposed, so there is no text found to save. Therefore, `on_exit` should, probably be actually called on Form.Close (when the main window of the application is closed).

**Comment by stantonxu** [comment] 2018-05-18 21:53
Thanks for the comments, @obulat . However, this doesn't make sense to me,

_When you click Exit Application in the menu, you call native App.Exit() function, which, in turn, checks if any windows are open and closes them. When closing the main window, it, again, calls Form.Close(), which, in turn, calls App.Exit()._

If this is true, the application exit will cause infinite loop, App.Exit()->Form.Close()->App.Exit()...

Will you go ahead to implement on_exit() in the interface? Or do you want me to create a pull request to do that? I might need more hint about how to do it.

**Comment by freakboy3742** [comment] 2018-05-19 17:53
@obulat I've had a look at this, and there is definitely some complicated logic required here.

I think the problem is being cause because the "application is now exiting" logic is getting mixed up with the "I want the application to exit" logic. 

At present, we have an `exit()` method on `App`; that is currently being used as an "I want the application to exit" method. However, @stantonxu's use case is "logic that I want to run when the application exits", which means you get into weird circular logic cases where the user requests the app to exit, which runs the "exit()" method, which runs the logic where the user requests the app to exit.

AFAICT, the solution is to separate the two use cases. The `exit()` method stays as a "Make the application exit" mechanism; then we add an `on_exit` signal handler. @stantonxu's use case would be to register an `on_exit` handler, which will be invoked regardless of whether you select "quit" from the main menu, or close the main window. 

The "ApplicationExit" winforms event then invokes the on_exit handler; regardless of whether the application exit was caused by the close button or a menu item, the handler will be invoked.

The only question that then remains is whether the ApplicationExit event occurs to late to do anything meaningful with the app itself. If it does, there may be some value in using the FormClosing event captured on the Main Window, rather than the ApplicationExit event on the App itself (it may be worthwhile catching that event *regardless* - however, Windows might require this approach because of the lifecycle of the app).

**Comment by stantonxu** [comment] 2018-05-29 20:41
@obulat , I would like to test your PR#522. Could you advice with the _on_exit you implemented, how should I call it on Mac and Windows? I mean how to set the handler of save_file?

**Comment by freakboy3742** [comment] 2018-05-30 01:17
Resolved by #522

**Closed by freakboy3742** 2018-05-30 01:17 UTC
